### ISSUE TITLE
Return associations on remove association

### ISSUE THREAD

**Issue by wbhob** [fabrix-app/spool-cart#28]
#### Issue Description
When removing an association (`DELETE /product/:product/association/:association`) it should also return the updated array of associations on the product (currently returns the product instance)

#### Environment
- node version: ???
- fabrix version: ???
- operating system: ???

**Comment by scott-wyatt** [comment]
It should technically return the association that was removed. That's part of some methodology that I can't remember the name of right now. But's basically like "Confirm that thing that was deleted so you can undo it"
